-- Run in an existing authorized database and warehouse. Uses a NEW schema.
-- Stop on any error; never continue if the schema already exists.
USE WAREHOUSE __WAREHOUSE__;
USE DATABASE __DATABASE__;
CREATE SCHEMA __DATABASE__.__SCHEMA__;
USE SCHEMA __DATABASE__.__SCHEMA__;

CREATE TABLE FLEET_DAILY (
  DATA DATE NOT NULL,
  EQUIPAMENTO_ID VARCHAR NOT NULL,
  EQUIPAMENTO VARCHAR NOT NULL,
  TIPO VARCHAR NOT NULL,
  AREA VARCHAR NOT NULL,
  PRODUCAO_TON NUMBER(18,1) NOT NULL,
  HORAS_OPERACAO NUMBER(12,2) NOT NULL,
  HORAS_CALENDARIO NUMBER(12,2) NOT NULL,
  HORAS_MANUTENCAO NUMBER(12,2) NOT NULL,
  HORAS_CORRETIVAS NUMBER(12,2) NOT NULL,
  FALHAS NUMBER(10,0) NOT NULL,
  CUSTO_MANUTENCAO NUMBER(18,2) NOT NULL,
  LITROS NUMBER(18,2) NOT NULL,
  CUSTO_COMBUSTIVEL NUMBER(18,2) NOT NULL,
  META_PRODUCAO_TON NUMBER(18,1) NOT NULL,
  PRIMARY KEY (DATA, EQUIPAMENTO_ID)
);
-- Standard-table PK is metadata; verify uniqueness in 03_quality.sql.
CREATE FILE FORMAT FLEET_CSV TYPE=CSV SKIP_HEADER=1
  FIELD_OPTIONALLY_ENCLOSED_BY='"' ENCODING='UTF8' ERROR_ON_COLUMN_COUNT_MISMATCH=TRUE;
CREATE STAGE FLEET_STAGE FILE_FORMAT=FLEET_CSV;
