USE DATABASE __DATABASE__;
USE SCHEMA __DATABASE__.__SCHEMA__;
-- Expected 5840 rows, 2025-01-01 through 2026-12-31, 8 equipment IDs.
SELECT COUNT(*) AS ROWS_LOADED, MIN(DATA) AS FIRST_DAY, MAX(DATA) AS LAST_DAY,
       COUNT(DISTINCT EQUIPAMENTO_ID) AS EQUIPMENT_COUNT FROM FLEET_DAILY;
-- Both following queries must return zero rows. Stop if they do not.
SELECT DATA, EQUIPAMENTO_ID, COUNT(*) AS N
FROM FLEET_DAILY GROUP BY DATA, EQUIPAMENTO_ID HAVING COUNT(*) <> 1;
SELECT * FROM FLEET_DAILY
WHERE HORAS_CORRETIVAS < 0 OR HORAS_CORRETIVAS > HORAS_MANUTENCAO
   OR HORAS_OPERACAO < 0 OR HORAS_MANUTENCAO > HORAS_CALENDARIO
   OR HORAS_OPERACAO + HORAS_MANUTENCAO > HORAS_CALENDARIO
   OR FALHAS NOT IN (0,1) OR (FALHAS=0 AND HORAS_CORRETIVAS<>0)
   OR (FALHAS=1 AND HORAS_CORRETIVAS<=0)
   OR PRODUCAO_TON < 0 OR CUSTO_MANUTENCAO < 0 OR CUSTO_COMBUSTIVEL < 0;
