{"name":"FleetAnalytics","compatibilityLevel":1600,"model":{"culture":"pt-BR","defaultPowerBIDataSourceVersion":"powerBI_V3","sourceQueryCulture":"en-US","tables":[{"name":"DimData","columns":[{"name":"Data","dataType":"dateTime","sourceColumn":"Data","summarizeBy":"none","isKey":true,"formatString":"dd/MM/yyyy","annotations":[{"name":"UnderlyingDateTimeDataType","value":"Date"}]},{"name":"Ano","dataType":"int64","sourceColumn":"Ano","summarizeBy":"none"},{"name":"Mes","dataType":"int64","sourceColumn":"Mes","summarizeBy":"none"},{"name":"AnoMes","dataType":"string","sourceColumn":"AnoMes","summarizeBy":"none"},{"name":"Dia","dataType":"int64","sourceColumn":"Dia","summarizeBy":"none"}],"partitions":[{"name":"DimData","mode":"import","source":{"type":"m","expression":["let","    Datas = List.Dates(#date(2025, 1, 1), 731, #duration(1,0,0,0)),","    Fonte = Table.FromList(Datas, Splitter.SplitByNothing(), {\"Data\"}),","    Tipos = Table.TransformColumnTypes(Fonte, {{\"Data\", type date}}),","    Ano = Table.AddColumn(Tipos, \"Ano\", each Date.Year([Data]), Int64.Type),","    Mes = Table.AddColumn(Ano, \"Mes\", each Date.Month([Data]), Int64.Type),","    AnoMes = Table.AddColumn(Mes, \"AnoMes\", each Date.ToText([Data], \"yyyy-MM\"), type text),","    Dia = Table.AddColumn(AnoMes, \"Dia\", each Date.Day([Data]), Int64.Type)","in","    Dia"]}}],"dataCategory":"Time"},{"name":"DimEquipamento","columns":[{"name":"EquipamentoID","dataType":"string","sourceColumn":"EquipamentoID","summarizeBy":"none","isKey":true},{"name":"Equipamento","dataType":"string","sourceColumn":"Equipamento","summarizeBy":"none"},{"name":"Tipo","dataType":"string","sourceColumn":"Tipo","summarizeBy":"none"},{"name":"Modelo","dataType":"string","sourceColumn":"Modelo","summarizeBy":"none"},{"name":"Area","dataType":"string","sourceColumn":"Area","summarizeBy":"none"}],"partitions":[{"name":"DimEquipamento","mode":"import","source":{"type":"m","expression":["let","    Fonte = #table(","        type table [EquipamentoID=text, Equipamento=text, Tipo=text, Modelo=text, Area=text],","        {","            {\"EQ-01\",\"Caminhão 01\",\"Caminhão\",\"CAT 777\",\"Mina Norte\"},","            {\"EQ-02\",\"Caminhão 02\",\"Caminhão\",\"CAT 777\",\"Mina Norte\"},","            {\"EQ-03\",\"Caminhão 03\",\"Caminhão\",\"Komatsu HD785\",\"Mina Sul\"},","            {\"EQ-04\",\"Caminhão 04\",\"Caminhão\",\"Komatsu HD785\",\"Mina Sul\"},","            {\"EQ-05\",\"Escavadeira 01\",\"Escavadeira\",\"CAT 6040\",\"Mina Norte\"},","            {\"EQ-06\",\"Escavadeira 02\",\"Escavadeira\",\"Liebherr R 9400\",\"Mina Sul\"},","            {\"EQ-07\",\"Carregadeira 01\",\"Carregadeira\",\"CAT 994\",\"Pilha\"},","            {\"EQ-08\",\"Trator 01\",\"Trator\",\"CAT D11\",\"Infraestrutura\"}","        })","in","    Fonte"]}}]},{"name":"FatoOperacao","columns":[{"name":"Data","dataType":"dateTime","sourceColumn":"Data","summarizeBy":"none","formatString":"dd/MM/yyyy","annotations":[{"name":"UnderlyingDateTimeDataType","value":"Date"}]},{"name":"EquipamentoID","dataType":"string","sourceColumn":"EquipamentoID","summarizeBy":"none"},{"name":"ProducaoTon","dataType":"double","sourceColumn":"ProducaoTon","summarizeBy":"sum","formatString":"#,0.0"},{"name":"HorasOperacao","dataType":"double","sourceColumn":"HorasOperacao","summarizeBy":"sum","formatString":"#,0.00"},{"name":"HorasCalendario","dataType":"double","sourceColumn":"HorasCalendario","summarizeBy":"sum","formatString":"#,0.00"}],"partitions":[{"name":"FatoOperacao","mode":"import","source":{"type":"m","expression":["let","    Datas = List.Dates(#date(2025, 1, 1), 731, #duration(1,0,0,0)),","    Equipamentos = {\"EQ-01\",\"EQ-02\",\"EQ-03\",\"EQ-04\",\"EQ-05\",\"EQ-06\",\"EQ-07\",\"EQ-08\"},","    Linhas = List.Combine(List.Transform(Datas, (d) => List.Transform(Equipamentos, (e) =>","        let","            Idx = Number.FromText(Text.End(e,2)),","            DiaAno = Date.DayOfYear(d),","            Horas = 15 + Number.Mod(DiaAno * 3 + Idx * 5, 8),","            Producao = Number.Round((110 + Idx * 9 + Number.Mod(DiaAno * 11 + Idx * 17, 75)) * Horas / 20, 1)","        in {d, e, Producao, Number.From(Horas), 24.0})),","    Fonte = Table.FromRows(Linhas, {\"Data\",\"EquipamentoID\",\"ProducaoTon\",\"HorasOperacao\",\"HorasCalendario\"}),","    Tipos = Table.TransformColumnTypes(Fonte, {{\"Data\", type date},{\"EquipamentoID\", type text},{\"ProducaoTon\", type number},{\"HorasOperacao\", type number},{\"HorasCalendario\", type number}})","in","    Tipos"]}}]},{"name":"FatoManutencao","columns":[{"name":"Data","dataType":"dateTime","sourceColumn":"Data","summarizeBy":"none","formatString":"dd/MM/yyyy","annotations":[{"name":"UnderlyingDateTimeDataType","value":"Date"}]},{"name":"EquipamentoID","dataType":"string","sourceColumn":"EquipamentoID","summarizeBy":"none"},{"name":"TipoParada","dataType":"string","sourceColumn":"TipoParada","summarizeBy":"none"},{"name":"HorasManutencao","dataType":"double","sourceColumn":"HorasManutencao","summarizeBy":"sum","formatString":"#,0.00"},{"name":"CustoManutencao","dataType":"double","sourceColumn":"CustoManutencao","summarizeBy":"sum","formatString":"R$ #,0.00"}],"partitions":[{"name":"FatoManutencao","mode":"import","source":{"type":"m","expression":["let","    Datas = List.Dates(#date(2025, 1, 1), 731, #duration(1,0,0,0)),","    Equipamentos = {\"EQ-01\",\"EQ-02\",\"EQ-03\",\"EQ-04\",\"EQ-05\",\"EQ-06\",\"EQ-07\",\"EQ-08\"},","    Linhas = List.Combine(List.Transform(Datas, (d) => List.Transform(Equipamentos, (e) =>","        let","            Idx = Number.FromText(Text.End(e,2)),","            DiaAno = Date.DayOfYear(d),","            TemFalha = Number.Mod(DiaAno + Idx * 7, 13 + Number.Mod(Idx,4)) = 0,","            Horas = if TemFalha then 2 + Number.Mod(DiaAno + Idx, 7) else 0,","            Tipo = if Number.Mod(DiaAno + Idx, 3)=0 then \"Corretiva\" else if Number.Mod(DiaAno + Idx, 3)=1 then \"Preventiva\" else \"Inspeção\",","            Custo = if TemFalha then Horas * (850 + Idx * 90) else 0","        in {d, e, Tipo, Number.From(Horas), Number.From(Custo)})),","    Fonte = Table.FromRows(Linhas, {\"Data\",\"EquipamentoID\",\"TipoParada\",\"HorasManutencao\",\"CustoManutencao\"}),","    Filtrado = Table.SelectRows(Fonte, each [HorasManutencao] > 0),","    Tipos = Table.TransformColumnTypes(Filtrado, {{\"Data\", type date},{\"EquipamentoID\", type text},{\"TipoParada\", type text},{\"HorasManutencao\", type number},{\"CustoManutencao\", type number}})","in","    Tipos"]}}]},{"name":"FatoAbastecimento","columns":[{"name":"Data","dataType":"dateTime","sourceColumn":"Data","summarizeBy":"none","formatString":"dd/MM/yyyy","annotations":[{"name":"UnderlyingDateTimeDataType","value":"Date"}]},{"name":"EquipamentoID","dataType":"string","sourceColumn":"EquipamentoID","summarizeBy":"none"},{"name":"Litros","dataType":"double","sourceColumn":"Litros","summarizeBy":"sum","formatString":"#,0.0"},{"name":"CustoCombustivel","dataType":"double","sourceColumn":"CustoCombustivel","summarizeBy":"sum","formatString":"R$ #,0.00"}],"partitions":[{"name":"FatoAbastecimento","mode":"import","source":{"type":"m","expression":["let","    Datas = List.Dates(#date(2025, 1, 1), 731, #duration(1,0,0,0)),","    Equipamentos = {\"EQ-01\",\"EQ-02\",\"EQ-03\",\"EQ-04\",\"EQ-05\",\"EQ-06\",\"EQ-07\",\"EQ-08\"},","    Linhas = List.Combine(List.Transform(Datas, (d) => List.Transform(Equipamentos, (e) =>","        let","            Idx = Number.FromText(Text.End(e,2)),","            DiaAno = Date.DayOfYear(d),","            Litros = 950 + Idx * 35 + Number.Mod(DiaAno * 19 + Idx * 31, 420),","            Preco = 5.35 + Number.Mod(DiaAno, 20) / 100","        in {d, e, Number.From(Litros), Number.Round(Litros * Preco, 2)})),","    Fonte = Table.FromRows(Linhas, {\"Data\",\"EquipamentoID\",\"Litros\",\"CustoCombustivel\"}),","    Tipos = Table.TransformColumnTypes(Fonte, {{\"Data\", type date},{\"EquipamentoID\", type text},{\"Litros\", type number},{\"CustoCombustivel\", type number}})","in","    Tipos"]}}]},{"name":"FatoMeta","columns":[{"name":"Data","dataType":"dateTime","sourceColumn":"Data","summarizeBy":"none","formatString":"dd/MM/yyyy","annotations":[{"name":"UnderlyingDateTimeDataType","value":"Date"}]},{"name":"EquipamentoID","dataType":"string","sourceColumn":"EquipamentoID","summarizeBy":"none"},{"name":"MetaProducaoTon","dataType":"double","sourceColumn":"MetaProducaoTon","summarizeBy":"sum","formatString":"#,0.0"}],"partitions":[{"name":"FatoMeta","mode":"import","source":{"type":"m","expression":["let","    Datas = List.Dates(#date(2025, 1, 1), 731, #duration(1,0,0,0)),","    Equipamentos = {\"EQ-01\",\"EQ-02\",\"EQ-03\",\"EQ-04\",\"EQ-05\",\"EQ-06\",\"EQ-07\",\"EQ-08\"},","    Linhas = List.Combine(List.Transform(Datas, (d) => List.Transform(Equipamentos, (e) =>","        let Idx = Number.FromText(Text.End(e,2)), Meta = 145 + Idx * 7 in {d, e, Number.From(Meta)})),","    Fonte = Table.FromRows(Linhas, {\"Data\",\"EquipamentoID\",\"MetaProducaoTon\"}),","    Tipos = Table.TransformColumnTypes(Fonte, {{\"Data\", type date},{\"EquipamentoID\", type text},{\"MetaProducaoTon\", type number}})","in","    Tipos"]}}]},{"name":"Medidas","columns":[{"name":"Chave","dataType":"int64","sourceColumn":"Chave","summarizeBy":"none","isHidden":true}],"partitions":[{"name":"Medidas","mode":"import","source":{"type":"m","expression":["let","    Fonte = #table(type table [Chave=Int64.Type], {{1}})","in","    Fonte"]}}],"measures":[{"name":"Produção Total","expression":"SUM(FatoOperacao[ProducaoTon])","formatString":"#,0.0"},{"name":"Horas Calendário","expression":"SUM(FatoOperacao[HorasCalendario])","formatString":"#,0.0"},{"name":"Horas Operação","expression":"SUM(FatoOperacao[HorasOperacao])","formatString":"#,0.0"},{"name":"Horas Manutenção","expression":"SUM(FatoManutencao[HorasManutencao])","formatString":"#,0.0"},{"name":"Disponibilidade Física %","expression":"DIVIDE([Horas Calendário] - [Horas Manutenção], [Horas Calendário])","formatString":"0.0%"},{"name":"Utilização %","expression":"DIVIDE([Horas Operação], [Horas Calendário] - [Horas Manutenção])","formatString":"0.0%"},{"name":"Produtividade t/h","expression":"DIVIDE([Produção Total], [Horas Operação])","formatString":"#,0.00"},{"name":"Litros Consumidos","expression":"SUM(FatoAbastecimento[Litros])","formatString":"#,0.0"},{"name":"Consumo L/t","expression":"DIVIDE([Litros Consumidos], [Produção Total])","formatString":"#,0.00"},{"name":"Custo Combustível","expression":"SUM(FatoAbastecimento[CustoCombustivel])","formatString":"R$ #,0.00"},{"name":"Custo Manutenção","expression":"SUM(FatoManutencao[CustoManutencao])","formatString":"R$ #,0.00"},{"name":"Custo Total","expression":"[Custo Combustível] + [Custo Manutenção]","formatString":"R$ #,0.00"},{"name":"Custo por Tonelada","expression":"DIVIDE([Custo Total], [Produção Total])","formatString":"R$ #,0.00"},{"name":"Falhas","expression":"COUNTROWS(FatoManutencao)","formatString":"#,0"},{"name":"MTTR","expression":"DIVIDE([Horas Manutenção], [Falhas])","formatString":"#,0.00"},{"name":"MTBF","expression":"DIVIDE([Horas Operação], [Falhas])","formatString":"#,0.00"},{"name":"Meta Produção","expression":"SUM(FatoMeta[MetaProducaoTon])","formatString":"#,0.0"},{"name":"Aderência Meta %","expression":"DIVIDE([Produção Total], [Meta Produção])","formatString":"0.0%"},{"name":"Produção Mês Anterior","expression":"CALCULATE([Produção Total], DATEADD(DimData[Data], -1, MONTH))","formatString":"#,0.0"},{"name":"Variação MoM %","expression":"DIVIDE([Produção Total] - [Produção Mês Anterior], [Produção Mês Anterior])","formatString":"0.0%"},{"name":"Produção Ano Anterior","expression":"CALCULATE([Produção Total], DATEADD(DimData[Data], -1, YEAR))","formatString":"#,0.0"},{"name":"Variação YoY %","expression":"DIVIDE([Produção Total] - [Produção Ano Anterior], [Produção Ano Anterior])","formatString":"0.0%"},{"name":"Produção Rolling 30d","expression":"CALCULATE([Produção Total], DATESINPERIOD(DimData[Data], MAX(DimData[Data]), -30, DAY))","formatString":"#,0.0"},{"name":"Produção Rolling 90d","expression":"CALCULATE([Produção Total], DATESINPERIOD(DimData[Data], MAX(DimData[Data]), -90, DAY))","formatString":"#,0.0"},{"name":"Ranking Equipamento","expression":"RANKX(ALLSELECTED(DimEquipamento[Equipamento]), [Produção Total], , DESC, DENSE)","formatString":"#,0"},{"name":"Participação Perdas %","expression":"DIVIDE([Horas Manutenção], CALCULATE([Horas Manutenção], ALLSELECTED(DimEquipamento[Equipamento])))","formatString":"0.0%"},{"name":"Perdas Acumuladas %","expression":"VAR RankAtual = [Ranking Criticidade] RETURN DIVIDE(SUMX(TOPN(RankAtual, ALLSELECTED(DimEquipamento[Equipamento]), [Horas Manutenção], DESC), [Horas Manutenção]), CALCULATE([Horas Manutenção], ALLSELECTED(DimEquipamento[Equipamento])))","formatString":"0.0%"},{"name":"Score Disponibilidade","expression":"1 - [Disponibilidade Física %]","formatString":"0.000"},{"name":"Score Falhas","expression":"VAR MaxFalhas = MAXX(ALLSELECTED(DimEquipamento[Equipamento]), [Falhas]) RETURN DIVIDE([Falhas], MaxFalhas)","formatString":"0.000"},{"name":"Score Custo","expression":"VAR MaxCusto = MAXX(ALLSELECTED(DimEquipamento[Equipamento]), [Custo por Tonelada]) RETURN DIVIDE([Custo por Tonelada], MaxCusto)","formatString":"0.000"},{"name":"Score Perda","expression":"VAR MaxPerda = MAXX(ALLSELECTED(DimEquipamento[Equipamento]), [Horas Manutenção]) RETURN DIVIDE([Horas Manutenção], MaxPerda)","formatString":"0.000"},{"name":"Índice Criticidade","expression":"0.35 * [Score Disponibilidade] + 0.25 * [Score Custo] + 0.20 * [Score Falhas] + 0.20 * [Score Perda]","formatString":"0.000"},{"name":"Ranking Criticidade","expression":"RANKX(ALLSELECTED(DimEquipamento[Equipamento]), [Índice Criticidade], , DESC, DENSE)","formatString":"#,0"},{"name":"Classe Criticidade","expression":"SWITCH(TRUE(), [Índice Criticidade] >= 0.70, \"Crítica\", [Índice Criticidade] >= 0.50, \"Alta\", [Índice Criticidade] >= 0.30, \"Média\", \"Baixa\")"}]}],"relationships":[{"name":"rel_FatoOperacao_data","fromTable":"FatoOperacao","fromColumn":"Data","toTable":"DimData","toColumn":"Data"},{"name":"rel_FatoOperacao_equip","fromTable":"FatoOperacao","fromColumn":"EquipamentoID","toTable":"DimEquipamento","toColumn":"EquipamentoID"},{"name":"rel_FatoManutencao_data","fromTable":"FatoManutencao","fromColumn":"Data","toTable":"DimData","toColumn":"Data"},{"name":"rel_FatoManutencao_equip","fromTable":"FatoManutencao","fromColumn":"EquipamentoID","toTable":"DimEquipamento","toColumn":"EquipamentoID"},{"name":"rel_FatoAbastecimento_data","fromTable":"FatoAbastecimento","fromColumn":"Data","toTable":"DimData","toColumn":"Data"},{"name":"rel_FatoAbastecimento_equip","fromTable":"FatoAbastecimento","fromColumn":"EquipamentoID","toTable":"DimEquipamento","toColumn":"EquipamentoID"},{"name":"rel_FatoMeta_data","fromTable":"FatoMeta","fromColumn":"Data","toTable":"DimData","toColumn":"Data"},{"name":"rel_FatoMeta_equip","fromTable":"FatoMeta","fromColumn":"EquipamentoID","toTable":"DimEquipamento","toColumn":"EquipamentoID"}]}}